### ISSUE TITLE
Endroid Qr code ?

### ISSUE THREAD

**Issue by Halfdann** [RikudouSage/QrPaymentCZ#25]
Am I doing something wrong or this is not complete solution.
There is a probably dependence for Endroid/Qrcode class which I found out but its not included in the download zip.
and probably even more.

If I create just simple page to generate qr code it is not working out of the box.
Is there some catch how to make it work?

`Fatal error: Uncaught Error: Class 'rikudou\CzQrPayment\QrPayment' not found in `

**Comment by RikudouSage** [comment]
You should use [composer](https://getcomposer.org/download/) to install it (if you don't know about composer, read more [here](https://getcomposer.org/doc/00-intro.md)), don't download the zip.

Install using `composer require rikudou/czqrpayment`.

If you don't want to use composer, you can manually require all of the files (but I strongly advise you to use composer):

```php
<?php

require_once __DIR__.'/path/to/library/QrPayment.php';
require_once __DIR__.'/path/to/library/QrPaymentException.php';
require_once __DIR__.'/path/to/library/QrPaymentOptions.php'; // this one is not needed, if you don't plan to use it
```

If you want to use the Endroid library to display QR codes, install it via composer: `composer require endroid/qr-code:^3.2`.
I'm not author of the endroid library so I cannot help with installing without composer. Alternatively you don't have to use the `getQrImage()` method (which calls the endroid library) and just call `getQrString()` and embed the result in a QR code in any other way.

**Comment by vasikgreif** [comment]
Getting the same error when using composer, the Edroid is marked as `suggest` in composer.json, should be required:

https://github.com/RikudouSage/QrPaymentCZ/blob/master/composer.json

**Comment by Halfdann** [comment]
I have switched for this plugin because it was not worth the effort when in hurry: 
[https://ceskepluginy.cz/produkty/woo-qr-platby/](url)

But I will try this QrPaymentCZ maybe in future if its ready to use "plug n play".

**Comment by RikudouSage** [comment]
@vasikgreif It's intended and documented behavior, I'm not forcing anyone to use `endroid/qr-code` if they already use something different. So requiring it with composer is not a temporary fix but the actual solution.

@Halfdann It can't be much more "plug n play" than running `composer require rikudou/czqrpayment` and `composer require endroid/qr-code`. If you're suggesting that buying a plugin is easier than running one command, I'm not really sure I can take you seriously. I mean, what's the process of buying the plugin? Adding to shopping cart, going to shopping cart, filling your information, filling your payment info, authorizing the payment and then waiting for it to arrive? Are you seriously implying it's an easier process than running `composer require endroid/qr-code`?

**Comment by vasikgreif** [comment]
Thanks. I don't see mentioning anywhere in the readme that `endroid/qr-code` is required. Maybe just updating the readme would help? Thanks!

**Comment by RikudouSage** [comment]
@vasikgreif I will update it a little. It's not required, if you use different QR code generator, you can just call `getQrString()` method and put it into your own QR code library.
