### ISSUE TITLE
Undefined method writeString()

### ISSUE THREAD

**Issue by sarry97** [RikudouSage/QrPaymentCZ#37]
Hi, I'm getting an error when creating qr image using Endroid generator. The full error is: **Uncaught Error: Call to undefined method Endroid\QrCode\QrCode::writeString() on $qrpayment->getQrImage()->writeString()** . The library is installed through composer. I'm a quite beginner at this, can somebody help me to solve this? Thanks.

**Comment by RikudouSage** [comment]
Hi, it uses `endroid/qr-code` library to display the QR code. You need to install it by running `composer require endroid/qr-code:^3.2`. If you installed a newer version, it's not guaranteed to work, but for the newest version it seems `getString()` should work (`$qrpayment->getQrImage()->getString()`).

**Comment by RikudouSage** [comment]
I reworked it a little, now you should be able to do this if you update to latest version and have any supported provider installed:

`$qrpayment->getQrCode()->getRawString()`

If you want to display it inside a html `<img>` tag, the method `getDataUri()` may come in handy, it allows you to do basically this:

`echo "<img src='{$qrpayment->getQrCode()->getDataUri()}'>";`

Currently supported providers (meaning you can just install them via `composer require` and it will work):

- `endroid/qr-code` version 3
- `endroid/qr-code` version 4
- `bacon/bacon-qr-code`
- `chillerlan/php-qrcode`

**Comment by RikudouSage** [comment]
Did you update to the latest version (`composer update` or `composer require rikudou/czqrpayment`)? In the latest version the `writeToFile()` method should be available. Can you post the whole error message?

**Comment by sarry97** [comment]
Yes, I have the latest version. Full error: `Fatal error: Uncaught Error: Call to undefined method Rikudou\CzQrPayment\QrPayment::writeToFile() in C:\xampp\htdocs\ADMINPHP\includes\cart.inc.php:867 Stack trace: #0 {main} thrown in C:\xampp\htdocs\ADMINPHP\includes\cart.inc.php on line 867` (`$qrpayment->writeToFile('../admin/upload/orders/qrpay/qrpay_'.$orderid.'.png');`).

**Comment by RikudouSage** [comment]
Ah, you're calling `writeToFile()` directly on the payment object, you need to do `$qrpayment->getQrCode()->writeToFile('../admin/upload/orders/qrpay/qrpay_'.$orderid.'.png')`.

Notice that I first call `$qrpayment->getQrCode()` and `writeToFile()` on the result of `getQrCode()`.

**Comment by sarry97** [comment]
Thank you so much, now it works properly. :)

**Comment by RikudouSage** [comment]
Glad I could help :)
