### ISSUE TITLE
Variable symbol - leading zeroes

### ISSUE THREAD

**Issue by tonyp90** [RikudouSage/QrPaymentCZ#40]
Czech variable symbol can contain max 10 numbers including leading zeroes. It's not possible to generate this QR, because VS parameter is an integer.

**Comment by RikudouSage** [comment]
I'll look into it and implement a fix, thanks!

**Comment by tonyp90** [comment]
Hello again and thanks for quick response. However, version 5.2.0 still generates QR code with variable symbol only "1", not required "00001".

$payment->setOptions([
            QrPaymentOptions::VARIABLE_SYMBOL => '00001',
            QrPaymentOptions::AMOUNT => 100,
            QrPaymentOptions::CURRENCY => "CZK"
]);

**Comment by RikudouSage** [comment]
Sorry, that was mistake on my part, should now be fixed and contains tests to ensure it will work.

**Comment by tonyp90** [comment]
Cool, thanks.
