### ISSUE TITLE
Support for PT parameter. 

### ISSUE THREAD

**Issue by vzikmund** [RikudouSage/QrPaymentCZ#43]
Hello, 
is it possible to implement support for PT parameter? I'd love to mark QR payment as instant by setting PT parameter to IP value `PT:IP*` (https://qr-platba.cz/pro-vyvojare/specifikace-formatu/)

I don't know where else to post it, so i am writing it here :) Would be lovely if you'd find time for adding it <3.

**Comment by RikudouSage** [comment]
Hello, I'll take a look into it!

**Comment by RikudouSage** [comment]
Released in 5.3.0 (https://github.com/RikudouSage/QrPaymentCZ/releases/tag/v5.3.0)!

**Comment by vzikmund** [comment]
:O Thank you!
